using System.Security.Cryptography;
using System.Text;

namespace Ordex.Web.Theming;

/// <summary>
/// Turns each <see cref="ThemeDefinition"/> into CSS custom properties for light and dark mode.
/// All derived colours are computed, and text colours are pushed until they meet WCAG contrast,
/// so even a very bright brand (neon blue, sunny yellow) stays readable.
///
/// Output looks like:
///   :root[data-palette="brattle"]:not([data-theme="dark"]) { --brand: #5bccf6; … }
///   :root[data-palette="brattle"][data-theme="dark"]       { … }
/// It is generated once per app start and served from /theme.css (cached, versioned).
/// </summary>
public static class ThemeCss
{
    private static readonly Lazy<(string Css, string Version)> Built = new(() =>
    {
        var css = BuildAll();
        var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(css)))[..12].ToLowerInvariant();
        return (css, hash);
    });

    public static string Css => Built.Value.Css;

    /// <summary>Changes whenever a palette changes – used as ?v= for browser caching.</summary>
    public static string Version => Built.Value.Version;

    /// <summary>Colour for the browser's address bar (meta theme-color).</summary>
    public static string ThemeColor(string? key, bool dark) =>
        dark ? DarkSidebar(ThemeCatalog.Get(key)).Hex : Rgb.Parse(ThemeCatalog.Get(key).Ink).Hex;

    private static string BuildAll()
    {
        var sb = new StringBuilder();
        sb.AppendLine("/* Ordex themes – generated by Ordex.Web/Theming/ThemeCss.cs. Do not edit by hand. */");
        foreach (var theme in ThemeCatalog.All)
        {
            Write(sb, $":root[data-palette=\"{theme.Key}\"]:not([data-theme=\"dark\"])", Light(theme), "light");
            Write(sb, $":root[data-palette=\"{theme.Key}\"][data-theme=\"dark\"]", Dark(theme), "dark");
        }
        return sb.ToString();
    }

    private static void Write(StringBuilder sb, string selector, IEnumerable<(string Name, string Value)> tokens, string scheme)
    {
        sb.Append(selector).AppendLine(" {");
        foreach (var (name, value) in tokens)
            sb.Append("  --").Append(name).Append(": ").Append(value).AppendLine(";");
        sb.Append("  color-scheme: ").Append(scheme).AppendLine(";");
        sb.AppendLine("}");
    }

    // ───────────────────────── Light ─────────────────────────
    private static IEnumerable<(string, string)> Light(ThemeDefinition t)
    {
        var ink = Rgb.Parse(t.Ink);
        var brand = Rgb.Parse(t.Brand);
        var accent = Rgb.Parse(t.Accent);
        var canvas = Rgb.Parse(t.Canvas);
        var white = Rgb.White;

        var bg = white.Mix(canvas, t.CanvasStrength);
        var surface = white;
        var text = ink.EnsureContrast(surface, 12);

        // Text-safe version of the brand for links, icons and labels.
        var primary = brand.EnsureContrast(surface, 4.5).EnsureContrast(bg, 4.5);
        var primarySoft = white.Mix(brand, 0.14);
        var accentSoft = white.Mix(accent, 0.22);

        return Common(brand, accent,
            bg: bg,
            surface: surface,
            surface2: white.Mix(ink, 0.025).Mix(canvas, t.CanvasStrength * 0.35),
            surface3: white.Mix(ink, 0.075),
            border: white.Mix(ink, 0.11),
            borderStrong: white.Mix(ink, 0.19),
            text: text,
            text2: text.Mix(white, 0.22).EnsureContrast(bg, 7),
            muted: text.Mix(white, 0.45).EnsureContrast(bg, 4.6),
            brandHover: brand.Darken(brand.IsLight ? 0.08 : 0.14),
            primary: primary,
            primaryHover: primary.Darken(0.14),
            primarySoft: primarySoft,
            primaryInk: brand.EnsureContrast(primarySoft, 6.5),
            accentSoft: accentSoft,
            accentInk: accent.EnsureContrast(accentSoft, 5.5),
            sideBg: ink,
            chart1: brand.EnsureContrast(surface, 2.2),
            chart2: white.Mix(ink, 0.2),
            chart3: accent.EnsureContrast(surface, 2.6),
            shadowTint: ink);
    }

    // ───────────────────────── Dark ─────────────────────────
    private static IEnumerable<(string, string)> Dark(ThemeDefinition t)
    {
        var brand = Rgb.Parse(t.Brand);
        var accent = Rgb.Parse(t.Accent);
        var white = Rgb.White;

        var bg = new Rgb(10, 13, 19).Mix(brand, 0.05);
        var surface = new Rgb(17, 22, 31).Mix(brand, 0.06);
        var text = new Rgb(231, 235, 242);

        var primary = brand.EnsureContrast(surface, 4.8);
        var primarySoft = surface.Mix(brand, 0.2);
        var accentSoft = surface.Mix(accent, 0.18);

        return Common(brand, accent,
            bg: bg,
            surface: surface,
            surface2: surface.Mix(white, 0.035),
            surface3: surface.Mix(white, 0.075),
            border: surface.Mix(white, 0.1),
            borderStrong: surface.Mix(white, 0.18),
            text: text,
            text2: new Rgb(182, 191, 207),
            muted: new Rgb(134, 145, 166).EnsureContrast(bg, 4.6),
            brandHover: brand.Lighten(0.1),
            primary: primary,
            primaryHover: primary.Lighten(0.14),
            primarySoft: primarySoft,
            primaryInk: brand.EnsureContrast(primarySoft, 6.5),
            accentSoft: accentSoft,
            accentInk: accent.EnsureContrast(accentSoft, 6),
            sideBg: DarkSidebar(t),
            chart1: brand.EnsureContrast(surface, 3),
            chart2: surface.Mix(white, 0.2),
            chart3: accent.EnsureContrast(surface, 3),
            shadowTint: Rgb.Black);
    }

    private static Rgb DarkSidebar(ThemeDefinition t) => new Rgb(6, 9, 14).Mix(Rgb.Parse(t.Brand), 0.04);

    // ───────────────────────── Shared token list ─────────────────────────
    private static IEnumerable<(string, string)> Common(
        Rgb brand, Rgb accent,
        Rgb bg, Rgb surface, Rgb surface2, Rgb surface3, Rgb border, Rgb borderStrong,
        Rgb text, Rgb text2, Rgb muted,
        Rgb brandHover, Rgb primary, Rgb primaryHover, Rgb primarySoft, Rgb primaryInk,
        Rgb accentSoft, Rgb accentInk, Rgb sideBg, Rgb chart1, Rgb chart2, Rgb chart3, Rgb shadowTint)
    {
        var white = Rgb.White;
        var sideText = white.Mix(sideBg, 0.2);
        var sideMuted = white.Mix(sideBg, 0.5).EnsureContrast(sideBg, 4.6);
        var dark = !bg.IsLight;

        yield return ("bg", bg.Hex);
        yield return ("surface", surface.Hex);
        yield return ("surface-2", surface2.Hex);
        yield return ("surface-3", surface3.Hex);
        yield return ("border", border.Hex);
        yield return ("border-strong", borderStrong.Hex);
        yield return ("text", text.Hex);
        yield return ("text-2", text2.Hex);
        yield return ("muted", muted.Hex);

        // Fills (buttons, ＋, active tab) keep the true brand colour.
        yield return ("brand", brand.Hex);
        yield return ("brand-hover", brandHover.Hex);
        yield return ("on-brand", brand.ReadableText().Hex);
        yield return ("brand-rgb", brand.Channels);

        // Text-safe brand for links, icons, labels.
        yield return ("primary", primary.Hex);
        yield return ("primary-hover", primaryHover.Hex);
        yield return ("primary-soft", primarySoft.Hex);
        yield return ("primary-ink", primaryInk.Hex);
        yield return ("on-primary", primary.ReadableText().Hex);
        yield return ("primary-rgb", primary.Channels);

        yield return ("accent", accent.Hex);
        yield return ("accent-soft", accentSoft.Hex);
        yield return ("accent-ink", accentInk.Hex);
        yield return ("on-accent", accent.ReadableText().Hex);

        yield return ("side-bg", sideBg.Hex);
        yield return ("side-bg-2", sideBg.Mix(white, 0.08).Hex);
        yield return ("side-text", sideText.Hex);
        yield return ("side-muted", sideMuted.Hex);
        yield return ("side-border", white.Alpha(0.08));

        yield return ("chart-1", chart1.Hex);
        yield return ("chart-2", chart2.Hex);
        yield return ("chart-3", chart3.Hex);

        yield return ("focus", $"0 0 0 3px {brand.Alpha(dark ? 0.4 : 0.32)}");
        yield return ("shadow-sm", $"0 1px 2px {shadowTint.Alpha(dark ? 0.3 : 0.05)}");
        yield return ("shadow", $"0 1px 2px {shadowTint.Alpha(dark ? 0.25 : 0.04)}, 0 6px 20px {shadowTint.Alpha(dark ? 0.25 : 0.06)}");
        yield return ("shadow-lg", $"0 16px 48px {shadowTint.Alpha(dark ? 0.5 : 0.16)}");
    }
}
